### ISSUE TITLE
Guard not Starting

### ISSUE THREAD

**Issue by redbassett** [cyphactor/sublime_guard#80]
Running ST3, Guard simply doesn't start when I run the start command. At first I thought my error was similar to #11 (like @ticktricktrack, there is no process running for Guard), however the error @dagobar found in the console differed from mine. I am getting the following:

> FileNotFoundError: [Errno 2] No such file or directory: '/Users/[username]/Library/Application Support/Sublime Text 3/Packages/Guard/guard_wrapper'

**Comment by redbassett** [comment]
Yeah, I was able to get it running by manually cloning the repo to the Packages folder and renaming it "Guard".

**Comment by nightpool** [comment]
fixed by #83
